zadanie 4 lekcja 8
MCaberGIT/FutureCollarsKurs pull request #13
Opened 2022-09-07 18:43 UTC by MCaberGIT

2022-09-15 17:36 UTC, BartoszKamyszek requested changes

2022-09-15 17:36 UTC, BartoszKamyszek commented on src/main/java/com/futurecollars/zad4/toLowerCaseFormatter.java
> +public class toLowerCaseFormatter implements TextFormatter {
Nazwy klas piszemy z wielkiej litery

2022-09-15 17:36 UTC, BartoszKamyszek commented on src/main/java/com/futurecollars/zad4/toUpperCaseFormatter.java
> +public class toUpperCaseFormatter implements TextFormatter {
jak wyżej

2022-09-15 17:36 UTC, BartoszKamyszek commented on src/test/java/com/futurecollars/zad4/toLowerCaseFormatterTest.java
> +public class toLowerCaseFormatterTest {
Nazwa z wielkiej litery

2022-09-22 13:44 UTC, MCaberGIT commented on src/test/java/com/futurecollars/zad4/toLowerCaseFormatterTest.java
> +public class toLowerCaseFormatterTest {
dodano zmiany :D

2022-09-23 15:58 UTC, BartoszKamyszek approved these changes

2022-09-23 16:53 UTC, merged