Dodano zadanie numer 1 Lekcja 7
MCaberGIT/FutureCollarsKurs pull request #5
Opened 2022-09-04 03:58 UTC by MCaberGIT

2022-09-19 13:27 UTC, BartoszKamyszek requested changes

2022-09-19 13:27 UTC, BartoszKamyszek commented on src/main/java/com/futurecollars/lesson7/zad1/CinemaSeats.java
> +public class CinemaSeats {
Klasa reprezentuje jedno miejsce w kinie, skąd ta liczba mnoga?

2022-09-19 13:27 UTC, BartoszKamyszek commented on src/main/java/com/futurecollars/lesson7/zad1/CinemaSeats.java
> +    private final int rowNumbers;
dlaczego liczba mnoga?

2022-09-21 19:20 UTC, MCaberGIT commented on src/main/java/com/futurecollars/lesson7/zad1/CinemaSeats.java
> +    private final int rowNumbers;
już poprawione

2022-09-23 15:44 UTC, BartoszKamyszek approved these changes
Teraz super :)

2022-09-23 16:56 UTC, merged